// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;  // Updated to modern Solidity version for security/gas optimizations

contract Local {  // Contract names should be capitalized (convention)

    // State variable: Stored permanently on the blockchain
    // - Costs gas to modify (20,000 gas for zero→non-zero, 5,000 gas for updates)
    uint256 public age = 10;  // 'public' auto-generates a getter function

    /**
     * @dev Getter function for 'age' (auto-generated by 'public' keyword)
     * @return The current value of 'age'
     * @notice No gas cost when called (view function)
     */
    // Note: This is redundant because 'public' already creates a getter
    // function getter() public view returns (uint256) {
    //     return age;
    // }

    /**
     * @dev Updates the 'age' state variable
     * @param newage The new value to set for 'age'
     * @notice Requires gas (modifies contract storage)
     */
    function setter(uint256 newage) public {
        age = newage;
    }

    // Public state variable: Automatically generates:
    // 1. A getter function: `marks() view returns (uint256)`
    // 2. No setter (would need a separate function for that)
    uint256 public marks = 50;

    /**
     * @dev Updates the 'marks' state variable
     * @param newMarks The new value to set for 'marks'
     */
    function setMarks(uint256 newMarks) public {
        marks = newMarks;
    }
}